name: ci-node-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.3

      - name: Install dependencies
        run: npm install
        
      - name: Run unit tests
        run: npm test